[build]
  command = "npm run build && npx react-snap"
  publish = "build"

[[redirects]]
  from = "http://financialdecisionmodels.com/*"
  to = "https://financialdecisionmodels.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.financialdecisionmodels.com/*"
  to = "https://www.financialdecisionmodels.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.financialdecisionmodels.com/*"
  to = "https://financialdecisionmodels.com/:splat"
  status = 301
  force = true
